# Generated by Django 3.0.5 on 2023-07-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_supportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.CharField(default='Fill in ', max_length=2000),
        ),
    ]
