# Generated by Django 3.0.5 on 2023-07-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_product_detailed_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
    ]
