# Generated by Django 3.0.5 on 2023-07-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20230723_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=40)),
                ('sub_product_image1', models.ImageField(upload_to='sub_product_image/')),
                ('sub_product_image2', models.ImageField(blank=True, null=True, upload_to='sub_product_image/')),
                ('sub_product_image3', models.ImageField(blank=True, null=True, upload_to='sub_product_image/')),
                ('detailed_description', models.CharField(max_length=2000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecom.Product')),
            ],
        ),
    ]
