# Generated by Django 3.0.5 on 2023-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20230724_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', ' Confirmed'), ('Tour Started', 'Tour Started'), ('Tour Ended', 'Tour Ended')], max_length=50, null=True),
        ),
    ]
